# fly.toml app configuration file generated for maui-relief on 2023-08-15T09:36:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maui-relief"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
